[build]
  publish = "dist"
  command = "pnpm build"

[functions]
  directory = "dist-api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Example environment variables - these should be set in Netlify UI
# ALCHEMY_API_KEY = "your_alchemy_api_key_here"
# WEB3_STORAGE = "your_web3_storage_api_key_here" 