[build]
  publish = "dist"
  command = "pnpm build"

[functions]
  directory = "dist-api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Required environment variables (set in Netlify UI):
# ALCHEMY_API_KEY - For token discovery via Alchemy API
# PINATA_JWT - For IPFS image uploads
# PINATA_GATEWAY - Pinata gateway URL 